# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ignac/Downloads/project_1/project_1.srcs/sources_1/ip/clk_wiz_50m/clk_wiz_50m.xci
# IP: The module: 'clk_wiz_50m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ignac/Downloads/project_1/project_1.srcs/sources_1/ip/clk_wiz_50m/clk_wiz_50m.xci
# IP: The module: 'clk_wiz_50m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ignac/Downloads/project_1/project_1.gen/sources_1/ip/clk_wiz_50m/clk_wiz_50m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
